concurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "docker-runner"
  url = "http://gitlab/"
  token = <gitlab_access_token>
  executor = "docker"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    privileged = true
    network_mode = "gitlab-network"
    disable_cache = false
    volumes = ["/certs/client", "/cache"]
    shm_size = 0
