apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-data-pv
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/opt/gitlab/data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-logs-pv
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/opt/gitlab/logs"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-config-pv
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/opt/gitlab/config"
---    
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---    
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi

---    
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-logs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
